Locales['fr'] = {
	-- Cloakroom
	['cloakroom'] = 'Vestiaire',
	['ems_clothes_civil'] = 'Fin de Service',
	['ems_clothes_ems'] = 'Prise de Service en Tenue Ambulancier',
	-- Vehicles
	['veh_menu'] = 'véhicule',
	['veh_spawn'] = 'appuyez sur ~INPUT_CONTEXT~ pour sortir un véhicule',
	['cacao'] = 'Sortir un véhicule',
	['store_veh'] = 'appuyez sur ~INPUT_CONTEXT~ pour ranger le véhicule',
	['ambulance'] = 'ambulance',
	['helicopter'] = 'hélicoptère',
	-- Action Menu
	['hospital'] = 'hôpital',
	['revive_inprogress'] = 'réanimation en cours',
	['revive_complete'] = 'vous avez réanimé ~y~%s~s~',
	['revive_complete_award'] = 'vous avez réanimé ~y~%s~s~, ~g~$%s~s~',
	['heal_inprogress'] = 'vous avez etait soigné!',
	['heal_complete'] = 'vous avez soigné ~y~%s~s~',
	['no_players'] = 'aucun joueur à proximité',
	['no_vehicles'] = 'aucun véhicule à proximité',
	['player_not_unconscious'] = 'n\'est pas inconscient',
	['player_not_conscious'] = 'Cette personne est inconsciente!',
	-- Boss Menu
	['deposit_society'] = 'déposer argent',
	['withdraw_society'] = 'retirer argent société',
	['boss_actions'] = 'action Patron',
	-- Misc
	['invalid_amount'] = '~r~montant invalide',
	['open_menu'] = 'appuyez sur ~INPUT_CONTEXT~ pour ouvrir le menu',
	['deposit_amount'] = 'montant du dépôt',
	['money_withdraw'] = 'montant du retrait',
	['fast_travel'] = 'appuyez sur ~INPUT_CONTEXT~ pour vous déplacer rapidement.',
	['open_pharmacy'] = 'appuyez sur ~INPUT_CONTEXT~ pour ouvrir la pharmacie.',
	['pharmacy_menu_title'] = 'Pharmacie',
	['pharmacy_take'] = 'Prendre',
	['medikit'] = 'kit de soin',
	['bandage'] = 'bandage',
	['max_item'] = 'vous en portez déjà assez sur vous.',
	['recup_police_items'] = 'Récupérer vos menottes',
	['billing'] = 'Factures',
	['invoice_amount'] = 'montant de la facture',
	['invoice_sent'] = 'Facture envoyé !',
	-- F6 Menu
	['ems_menu'] = 'interaction citoyen',
	['ems_menu_title'] = 'ambulance - Interactions Citoyen',
	['ems_menu_revive'] = 'réanimer',
	['ems_menu_putincar'] = 'mettre dans véhicule',
	['ems_menu_small'] = 'soigner petites blessures',
	['ems_menu_big'] = 'soigner blessures graves',
	-- Phone
	['alert_ambulance'] = 'alerte Ambulance',
	-- Death
	['please_wait'] = 'Réapparition dans ~g~%s minutes',
	['press_respawn'] = '~s~appuyez sur [~g~E~s~] pour réapparaître.',
	['respawn_now_fine'] = 'réapparaître maintenant pour ~g~$%s ~s~[Appuyez ~b~E~s~]',
	['respawn_fine'] = 'vous avez payez ~r~$%s~s~ pour réapparaître.',
	['distress_send'] = 'appuyez sur [~g~G~s~] pour envoyer un signal de détresse',
	['distress_sent'] = 'le signal de détresse a été envoyé aux unités disponibles!',
	['distress_message'] = 'attention médicale requise: citoyen inconscient!',
	['combatlog_message'] = 'vous avez été réanimé de force car vous avez quitté le serveur.',
	-- Revive
	['revive_help'] = 'relancer un joueur',
	-- Item
	['used_medikit'] = 'vous avez utilisé 1x kit de soin',
	['used_bandage'] = 'vous avez utilisé 1x bandage',
	['not_enough_medikit'] = 'vous n\'avez pas de ~b~kit de soin~s~.',
	['not_enough_bandage'] = 'vous n\'avez pas de ~b~bandage~s~.',
	['healed'] = 'vous avez été soigné.',

	['cloakroom'] = 'Vestiaire',
	['vine_clothes_civil'] = 'Tenue Civil',
	['vine_clothes_vine'] = 'Tenue de travail',
	['veh_menu'] = 'Garage',
	['spawn_veh'] = 'appuyez sur ~INPUT_CONTEXT~ pour sortir véhicule',
	['amount_invalid'] = 'montant invalide',
	['press_to_open'] = 'appuyez sur ~INPUT_CONTEXT~ pour accéder au menu',
	['open_menu_bennys'] = 'Bennys Menu',
	['billing'] = 'facturation',
	['invoice_amount'] = 'montant de la facture',
	['no_players_near'] = 'aucun joueur à proximité',
	['store_veh'] = 'appuyez sur ~INPUT_CONTEXT~ pour ranger le véhicule',
	['comp_earned'] = 'votre société a gagné ~g~$',
	['deposit_stock'] = 'Déposer Stock',
	['take_stock'] = 'Prendre Stock',
	['boss_actions'] = 'action Patron',
	['quantity'] = 'Quantité',
	['quantity_invalid'] = '~r~Quantité invalide~s~',
	['inventory'] = 'Inventaire',
	['have_withdrawn'] = 'Vous avez retiré x',
	['added'] = 'Vous avez ajouté x',
	['not_enough_place'] = 'Vous n\'avez plus de place',
	['sale_in_prog'] = 'Revente en cours...',
	['van'] = 'Camion de travail',
	['open_menu'] = ' ',
	['avocat_client'] = 'client avocat',
	['transforming_in_progress'] = 'Transformation du raisin en cours',
	['raisin_taken'] = 'Vous être en train de ramasser du raisin',
	['press_traitement'] = 'appuyez sur ~INPUT_CONTEXT~ pour transformer votre raisin',
	['press_collect'] = 'appuyez sur ~INPUT_CONTEXT~ pour récolter du raisin',
	['press_sell'] = 'appuyez sur ~INPUT_CONTEXT~ pour vendre vos produits',
	['no_jus_sale'] = 'Vous n\'avez plus ou pas assez de jus de raisin',
	['no_vin_sale'] = 'Vous n\'avez plus ou pas assez de vin',
	['not_enough_raisin'] = 'Vous n\'avez plus de raisin',
	['grand_cru'] = '~g~Génial, un grand cru !~s~',
	['no_product_sale'] = 'Vous n\'avez plus de produits',
	['press_traitement_jus'] = 'appuyez sur ~INPUT_CONTEXT~ pour transformer votre raisin',
	['used_jus'] = 'Vous avez bu du jus de raisin',
	['used_grand_cru'] = 'Vous avez bu une bouteille de grand cru',


	['by_default'] = 'par défaut',
	['installed'] = 'installé',
	['already_own'] = 'vous possédez déjà: ~b~%s~s~',
	['not_enough_money'] = 'vous n\'avez pas assez d\'argent!',
	['purchased'] = 'achat effectué!',
	['press_custom'] = 'appuyez sur ~INPUT_PICKUP~ pour personnaliser le véhicule.',
	['level'] = 'niveau %s',
	['neon'] = 'neon',
	['blip_name'] = 'los Santos Customs',
	-- Paint Colors
	-- Black
	['black'] = 'noir',
	['graphite'] = 'graphite',
	['black_metallic'] = 'noir Méttallisé',
	['caststeel'] = 'acier Fondu',
	['black_anth'] = 'noir Anthracite',
	['matteblack'] = 'noir Mat',
	['darknight'] = 'nuit Sombre',
	['deepblack'] = 'noir Profond',
	['oil'] = 'pétrol',
	['carbon'] = 'carbon',
	-- White
	['white'] = 'blanc',
	['vanilla'] = 'vanille',
	['creme'] = 'crème',
	['polarwhite'] = 'blanc Polair',
	['beige'] = 'beige',
	['mattewhite'] = 'blanc Mat',
	['snow'] = 'neige',
	['cotton'] = 'coton',
	['alabaster'] = 'albâtre',
	['purewhite'] = 'blanc Pure',
	-- Grey
	['grey'] = 'gris',
	['silver'] = 'Argenté',
	['metallicgrey'] = 'Gris Métallisé',
	['laminatedsteel'] = 'Acier Laminé',
	['darkgray'] = 'Gris Foncé',
	['rockygray'] = 'Gris Rocheux',
	['graynight'] = 'Gris Nuit',
	['aluminum'] = 'Aluminium',
	['graymat'] = 'Gris Mat',
	['lightgrey'] = 'Gris Clair',
	['asphaltgray'] = 'Gris Bitume',
	['grayconcrete'] = 'Gris Béton',
	['darksilver'] = 'Argent Sombre',
	['magnesite'] = 'Magnésite',
	['nickel'] = 'nickel',
	['zinc'] = 'zinc',
	['dolomite'] = 'dolomite',
	['bluesilver'] = 'Argent Bleuté',
	['titanium'] = 'Titane',
	['steelblue'] = 'Acier Bleui',
	['champagne'] = 'Champagne',
	['grayhunter'] = 'Gris Chasseur',
	-- Red
	['red'] = 'rouge',
	['torino_red'] = 'Rouge Turin',
	['poppy'] = 'Coquelicot',
	['copper_red'] = 'Rouge Cuivré',
	['cardinal'] = 'Rouge Cardinal',
	['brick'] = 'Rouge Brique',
	['garnet'] = 'Grenat',
	['cabernet'] = 'Pourpre',
	['candy'] = 'Framboise',
	['matte_red'] = 'Rouge Mat',
	['dark_red'] = 'Rouge Foncé',
	['red_pulp'] = 'Rouge Pulpeux',
	['bril_red'] = 'Rouge Brillant',
	['pale_red'] = 'Rouge Pale',
	['wine_red'] = 'Rouge Vin',
	['volcano'] = 'Volcano',
	-- Pink
	['pink'] = 'rose',
	['electricpink'] = 'rose Electrique',
	['brightpink'] = 'rose pétant',
	['salmon'] = 'rose Saumon',
	['sugarplum'] = 'rose Dragée',
	-- Blue
	['blue'] = 'bleu',
	['topaz'] = 'topaze',
	['light_blue'] = 'bleu clair',
	['galaxy_blue'] = 'bleu galaxy',
	['dark_blue'] = 'bleu foncé',
	['azure'] = 'bleu azur',
	['navy_blue'] = 'bleu marine',
	['lapis'] = 'lapis lazuli',
	['blue_diamond'] = 'bleu diamant',
	['surfer'] = 'surfer',
	['pastel_blue'] = 'pastel',
	['celeste_blue'] = 'bleu celeste',
	['rally_blue'] = 'bleu rally',
	['blue_paradise'] = 'bleu paradis',
	['blue_night'] = 'bleu nuit',
	['cyan_blue'] = 'bleu cyan',
	['cobalt'] = 'cobalt',
	['electric_blue'] = 'bleu electrique',
	['horizon_blue'] = 'bleu horizon',
	['metallic_blue'] = 'bleu métallisé',
	['aquamarine'] = 'aigue marine',
	['blue_agathe'] = 'bleu agathe',
	['zirconium'] = 'zirconium',
	['spinel'] = 'spinelle',
	['tourmaline'] = 'tourmaline',
	['paradise'] = 'paradis',
	['bubble_gum'] = 'bubble gum',
	['midnight_blue'] = 'bleu minuit',
	['forbidden_blue'] = 'bleu interdit',
	['glacier_blue'] = 'bleu glacier',
	-- Yellow
	['yellow'] = 'jaune',
	['wheat'] = 'Jaune Blé',
	['raceyellow'] = 'Jaune Rally',
	['paleyellow'] = 'Jaune Clair',
	['lightyellow'] = 'Jaune Pâle',
	-- Green
	['green'] = 'vert',
	['met_dark_green'] = 'Vert Foncé',
	['rally_green'] = 'Vert Rally',
	['pine_green'] = 'Vert Sapin',
	['olive_green'] = 'Vert Olive',
	['light_green'] = 'Vert Clair',
	['lime_green'] = 'Vert Lime',
	['forest_green'] = 'Vert Forêt',
	['lawn_green'] = 'Vert Pelouse',
	['imperial_green'] = 'Vert Impérial',
	['green_bottle'] = 'Vert Bouteille',
	['citrus_green'] = 'Vert Citrus',
	['green_anis'] = 'Vert Anis',
	['khaki'] = 'Kaki',
	['army_green'] = 'Vert Army',
	['dark_green'] = 'Vert Sombre',
	['hunter_green'] = 'Vert Chasseur',
	['matte_foilage_green'] = 'Amarylisse',
	-- Orange
	['orange'] = 'orange',
	['tangerine'] = 'Tangerine',
	['matteorange'] = 'Orange Mat',
	['lightorange'] = 'Orange Clair',
	['peach'] = 'Pèche',
	['pumpkin'] = 'Citrouille',
	['orangelambo'] = 'Orange Lambo',
	-- Brown
	['brown'] = 'marron',
	['copper'] = 'Cuivre',
	['lightbrown'] = 'Marronclair',
	['darkbrown'] = 'Marron Foncé',
	['bronze'] = 'Bronze',
	['brownmetallic'] = 'Marron Métallisé',
	['espresso'] = 'Expresso',
	['chocolate'] = 'Chocolat',
	['terracotta'] = 'Terre Cuite',
	['marble'] = 'Marbre',
	['sand'] = 'Sable',
	['sepia'] = 'Sépia',
	['bison'] = 'Bison',
	['palm'] = 'Palmier',
	['caramel'] = 'Caramel',
	['rust'] = 'Rouille',
	['chestnut'] = 'Chataigne',
	['hazelnut'] = 'Noisette',
	['shell'] = 'Coquillage',
	['mahogany'] = 'Acajou',
	['cauldron'] = 'Chaudron',
	['blond'] = 'Blond',
	['gravel'] = 'Gravillon',
	['darkearth'] = 'Terre Foncé',
	['desert'] = 'Désert',
	-- Purple
	['purple'] = 'violet',
	['indigo'] = 'Indigo',
	['deeppurple'] = 'Violet Profond',
	['darkviolet'] = 'Violet Foncé',
	['amethyst'] = 'Améthyste',
	['mysticalviolet'] = 'Violet Mystique',
	['purplemetallic'] = 'Violet Métallisé',
	['matteviolet'] = 'Violet Mat',
	['mattedeeppurple'] = 'Violet Profond Mat',
	-- Chrome
	['chrome'] = 'chrome',
	['brushedchrome'] = 'chrome Brossé',
	['blackchrome'] = 'chrome Noir',
	['brushedaluminum'] = 'aluminum Brossé',
	-- Metal
	['gold'] = 'or',
	['puregold'] = 'Or Pure',
	['brushedgold'] = 'Or Brossé',
	['lightgold'] = 'Or Clair',
	-- License Plates
	['blue_on_white_1'] = 'bleu sur fond Blanc 1',
	['yellow_on_black'] = 'jaune sur fond Noir',
	['yellow_blue'] = 'jaune sur fond Bleu',
	['blue_on_white_2'] = 'bleu sur fond Blanc 2',
	['blue_on_white_3'] = 'bleu sur fond Blanc 3',
	-- Upgrades
	['upgrades'] = 'upgrades',
	['engine'] = 'moteur',
	['brakes'] = 'freins',
	['transmission'] = 'transmission',
	['suspension'] = 'suspension',
	['armor'] = 'armure',
	['turbo'] = 'turbo',
	['no_turbo'] = 'pas de turbo',
	-- Cosmetics
	['cosmetics'] = 'cosmétiques',
	-- Body Parts
	['bodyparts'] = 'carosserie',
	['leftfender'] = 'aile gauche',
	['rightfender'] = 'aile droite',
	['spoilers'] = 'aileron',
	['sideskirt'] = 'bas de caisse',
	['cage'] = 'cage',
	['hood'] = 'capot',
	['grille'] = 'grille',
	['rearbumper'] = 'pare-choc arrière',
	['frontbumper'] = 'pare-choc avant',
	['exhaust'] = 'pot d\'échappement',
	['roof'] = 'toit',
	-- Paint
	['respray'] = 'peinture',
	['primary'] = 'primaire',
	['secondary'] = 'secondaire',
	['pearlescent'] = 'nacré',
	-- Misc
	['headlights'] = 'phares',
	['licenseplates'] = 'plaque',
	['windowtint'] = 'fenêtres',
	['horns'] = 'klaxon',
	-- Neon
	['neons'] = 'néons',
	-- Wheels
	['wheels'] = 'roues',
	['tiresmoke'] = 'fumée des pneus',
	['wheel_type'] = 'types de Jantes',
	['wheel_color'] = 'couleurs jantes',
	['sport'] = 'Jantes Sport',
	['muscle'] = 'Jantes Muscle',
	['lowrider'] = 'Jantes Lowrider',
	['suv'] = 'Jantes SUV',
	['allterrain'] = 'Jantes Tout-terrain',
	['tuning'] = 'Jantes Tuning',
	['motorcycle'] = 'Jantes Moto',
	['highend'] = 'Jantes Haut de gamme',

	['modplateholder'] = 'plaque - Arrière',
	['modvanityplate'] = 'plate - Avant',
	['interior'] = 'intérieur',
	['trim'] = 'accessoires',
	['dashboard'] = 'tableau de bord',
	['speedometer'] = 'compteur de vitesse',
	['door_speakers'] = 'haut-parleurs - portières',
	['seats'] = 'sièges',
	['steering_wheel'] = 'volant',
	['gear_lever'] = 'levier de vitesse',
	['quarter_deck'] = 'plage arrière',
	['speakers'] = 'haut-parleurs',
	['trunk'] = 'coffre',
	['hydraulic'] = 'suspension hydraulique',
	['engine_block'] = 'bloc moteur',
	['air_filter'] = 'filtre à air',
	['struts'] = 'entretoises',
	['arch_cover'] = 'pare-boue des ailes',
	['aerials'] = 'antennes',
	['wings'] = 'ailes',
	['fuel_tank'] = 'bouchon du réservoir',
	['windows'] = 'fenêtres',
	['stickers'] = 'autocollants',

	['gilet_wear1'] = 'Enlever votre gilet orange',
	['cloakroom'] = 'vestiaire',
	['citizen_wear'] = 'Prendre sa fin de service',
	['douane1_wear'] = 'Prendre son service ✅',
	['gilet_wear'] = 'gilet orange',
	['bullet_wear'] = 'gilet pare-balles',
	['no_outfit'] = 'il n\'y a pas d\'uniforme à votre taille...',
	['open_cloackroom'] = 'appuyez sur ~INPUT_CONTEXT~ pour vous changer',
	-- Armory
	['remove_object'] = 'prendre un Objet',
	['deposit_object'] = 'deposer un objet',
	['get_weapon'] = 'prendre une Arme',
	['put_weapon'] = 'deposer une Arme',
	['buy_weapons'] = 'acheter des Armes',
	['armory'] = 'armurerie',
	['open_armory'] = 'appuyez sur ~INPUT_CONTEXT~ pour ouvrir le coffre de l\'armurerie',
	['armory_owned'] = 'possédé',
	['armory_free'] = 'gratuit',
	['armory_item'] = '$%s',
	['armory_weapontitle'] = 'armurerie - Acheter une arme',
	['armory_componenttitle'] = 'armurerie - Accessoires d\'armes',
	['armory_bought'] = 'vous achetez un ~y~%s~s~ pour ~r~$%s~s~',
	['armory_money'] = 'vous ne pouvez pas acheter cette arme',
	['armory_hascomponent'] = 'vous avez cet accessoire équipé!',
	['get_weapon_menu'] = 'armurerie - Prendre Arme',
	['put_weapon_menu'] = 'armurerie - Déposer Arme',
	-- Vehicles
	['vehicle_menu'] = 'VOS VEHICULES DE SERVICE',
	['vehicle_out'] = 'il y a déja un véhicule de sorti',
	['vehicle_spawner'] = 'appuyez sur ~INPUT_CONTEXT~ pour sortir un véhicule de service',
	['store_vehicle'] = 'appuyez sur ~INPUT_CONTEXT~ pour ranger votre véhicule de service',
	-- Service
	['service_max'] = 'you cannot enter service, max officers in service: %s/%s',
	['service_not'] = '~r~Tu n\'es pas en service',
	['service_anonunce'] = 'service information',
	['service_in'] = '~y~Prise de Service~s~',
	['service_in_announce'] = 'L\'officier ~y~%s~s~ est entrer service!',
	['service_out'] = '~y~Fin de Service~s~',
	['service_out_announce'] = 'L\'officier ~y~%s~s~ a pris sa fin de service.',
	-- Action Menu
	['citizen_interaction'] = 'interaction avec le citoyen',
	['vehicle_interaction'] = 'interaction avec le vehicule',
	['object_spawner'] = 'sortir du materiel',

	['id_card'] = 'Regarder la carte d\'identite',
	['search'] = 'fouiller l\'individu',
	['handcuff'] = 'menotter ou Demenotter',
	['drag'] = 'escorter l\'individu',
	['put_in_vehicle'] = 'mettre l\'individu dans le vehicule',
	['out_the_vehicle'] = 'sortir l\'individu du vehicule',
	['fine'] = 'Amende',
	['unpaid_bills'] = 'gerer les amendes impayes',
	['license_check'] = 'gerer les licences',
	['license_revoke'] = 'revoquer la licence',
	['license_revoked'] = 'votre ~b~%s~s~ a été ~y~révoqué~s~!',
	['licence_you_revoked'] = 'vous avez révoqué un ~b~%s~s~ qui appartenait à ~y~%s~s~',
	['no_players_nearby'] = 'aucun joueur à proximité',
	['being_searched'] = 'vous vous faites ~y~fouillé~s~ par un ~b~Douanier~s~',
	-- Vehicle interaction
	['vehicle_info'] = 'infos du véhicule',
	['pick_lock'] = 'crocheter le véhicule',
	['vehicle_unlocked'] = 'véhicule ~g~déverouillé~s~',
	['no_vehicles_nearby'] = 'aucun véhicule à proximité',
	['impound'] = 'véhicule en fourrière',
	['impound_prompt'] = 'appuyez sur ~INPUT_CONTEXT~ pour annuler la ~y~saisie du véhicule~s~',
	['impound_canceled'] = 'vous avez annulé la saisie',
	['impound_canceled_moved'] = 'la saisie a été annulée parce que le véhicule a déménagé',
	['impound_successful'] = 'vous avez ~r~saisi~s~ le véhicule',
	['search_database'] = 'vehicle information',
	['search_database_title'] = 'informations sur le véhicule - recherche avec numéro d\'enregistrement',
	['search_database_error_invalid'] = 'ce n\'est ~r~pas~s~ un ~y~numéro d\'enregistrement valide~s~ !',
	['search_database_error_not_found'] = 'ce ~y~numéro d\'enregistrement~s~ n\'est ~r~pas~s~ enregistré sur un véhicule !',
	['search_database_found'] = 'le véhicule est ~y~enregistré~s~ à ~b~%s~s~',
	-- Traffic interaction
	['traffic_interaction'] = 'Interaction routère',
	['cone'] = 'Plot',
	['mur'] = 'Petite Barrière en béton',
	['barrier'] = 'Barriere',
	['spikestrips'] = 'Herse',
	['box'] = 'caisse',
	['cash'] = 'caisse',
	-- ID Card Menu
	['name'] = 'nom: %s',
	['job'] = 'job: %s',
	['sex'] = 'sexe: %s',
	['dob'] = 'DDN: %s',
	['height'] = 'taille: %s',
	['id'] = 'ID: %s',
	['bac'] = 'alcoolémie: %s',
	['unknown'] = 'inconnu',
	['male'] = 'masculin',
	['female'] = 'féminin',
	-- Body Search Menu
	['guns_label'] = '--- Armes ---',
	['inventory_label'] = '--- Inventaire ---',
	['license_label'] = ' --- Licenses ---',
	['confiscate'] = 'Confisquer %s',
	['confiscate_weapon'] = 'confiscate %s with %s bullets',
	['confiscate_inv'] = 'Confisquer %sx %s',
	['confiscate_dirty'] = 'Confisquer argent sale: <span style="color:red;">€%s</span>',
	['you_confiscated'] = 'you confiscated ~y~%sx~s~ ~b~%s~s~ from ~b~%s~s~',
	['got_confiscated'] = '~y~%sx~s~ ~b~%s~s~ were confiscated by ~y~%s~s~',
	['you_confiscated_account'] = 'you confiscated ~g~€%s~s~ (%s) from ~b~%s~s~',
	['got_confiscated_account'] = '~g~€%s~s~ (%s) was confiscated by ~y~%s~s~',
	['you_confiscated_weapon'] = 'you confiscated ~b~%s~s~ from ~b~%s~s~ with ~o~%s~s~ bullets',
	['got_confiscated_weapon'] = 'your ~b~%s~s~ with ~o~%s~s~ bullets was confiscated by ~y~%s~s~',
	['traffic_offense'] = 'infraction au code de la route',
	['minor_offense'] = 'délit mineur',
	['average_offense'] = 'délit moyen',
	['major_offense'] = 'délit grave',
	['fine_total'] = 'amende: %s',
	-- Vehicle Info Menu
	['plate'] = 'n°: %s',
	['owner_unknown'] = 'propriétaire: Inconnu',
	['owner'] = 'propriétaire: %s',
	-- Boss Menu
	['take_company_money'] = 'retirer argent société',
	['deposit_money'] = 'déposer argent',
	['amount_of_withdrawal'] = 'montant du retrait',
	['invalid_amount'] = 'montant invalide',
	['amount_of_deposit'] = 'montant du dépét',
	['open_bossmenu'] = 'appuyez sur ~INPUT_CONTEXT~ pour ouvrir le menu',
	['quantity_invalid'] = 'quantité invalide',
	['have_withdrawn'] = 'vous avez retiré ~y~%sx~s~ ~b~%s~s~',
	['have_deposited'] = 'vous avez déposé ~y~%sx~s~ ~b~%s~s~',
	['quantity'] = 'quantité',
	['inventory'] = 'inventaire',
	['douane1_stock'] = 'Shériff Stock',
	-- Misc
	['remove_prop'] = 'appuyez sur ~INPUT_CONTEXT~ pour enlever l\'objet',
	--['map_blip'] = 'Commissariat',
	['unrestrained_timer'] = 'you feel your handcuffs slowly losing grip and fading away.',
	-- Notifications
	['alert_douane1'] = 'alerte police',
	['phone_douane1'] = 'douane1',
	['Brottsregister'] = 'Casier Judiciare',


	['new_job'] = 'vous avez un ~g~nouveau~s~ job !',
	['access_job_center'] = 'appuyez sur ~INPUT_PICKUP~ pour \naccéder au ~b~Pôle Emploi~s~.',
	['job_center'] = 'pôle-Emploi',


	['cloakroom'] = 'Vestiaire',
	['citizen_wear'] = 'Tenue civile',
	['journalist_outfit'] = 'Tenue de stagiaire',
	['journalist_outfit_1'] = 'Tenue de reporter',
	['journalist_outfit_2'] = 'Tenue d\'enquêteur',
	['journalist_outfit_3'] = 'Tenue de directeur',
	['no_outfit'] = 'Il n\'y a pas d\'uniforme à votre taille...',
	['open_cloackroom'] = 'Appuyez sur ~INPUT_CONTEXT~ pour vous changer',

	-- Vehicles
	['vehicle_menu'] = 'Véhicule',
	['vehicle_out'] = 'Il y a déja un véhicule dehors',
	['vehicle_spawner'] = 'Appuyez sur ~INPUT_CONTEXT~ pour sortir un véhicule',
	['store_vehicle'] = 'Appuyez sur ~INPUT_CONTEXT~ pour ranger le véhicule',
	['service_max'] = 'Service complet : ',
	['spawn_point_busy'] = 'Un véhicule occupe le point de sortie',

	-- Vault
	['get_weapon'] = 'Prendre Arme',
	['put_weapon'] = 'Déposer Arme',
	['get_weapon_menu'] = 'Coffre - Prendre Arme',
	['put_weapon_menu'] = 'Coffre - Déposer Arme',
	['get_object'] = 'Prendre Objet',
	['put_object'] = 'Déposer Objet',
	['vault'] = 'Coffre',
	['open_vault'] = 'Appuyez sur ~INPUT_CONTEXT~ pour accéder au coffre',

	-- Boss Menu
	['deposit_society'] = 'déposer argent',
	['withdraw_society'] = 'retirer argent société',
	['boss_actions'] = 'action Patron',
	['take_company_money'] = 'Retirer argent société',
	['deposit_money'] = 'Déposer argent',
	['amount_of_withdrawal'] = 'Montant du retrait',
	['amount_of_deposit'] = 'Montant du dépôt',
	['open_bossmenu'] = 'Appuyez sur ~INPUT_CONTEXT~ pour ouvrir le menu',
	['invalid_quantity'] = 'Quantité invalide',
	['you_removed'] = 'Vous avez retiré x',
	['you_added'] = 'Vous avez ajouté x',
	['quantity'] = 'Quantité',
	['inventory'] = 'Inventaire',
	['unicorn_stock'] = 'Stock',

	-- Misc
	--['map_blip'] = 'CNN',
	['invalid_amount'] = '~r~montant invalide',
	['open_menu'] = 'appuyez sur ~INPUT_CONTEXT~ pour ouvrir le menu',
	['deposit_amount'] = 'montant du dépôt',
	['money_withdraw'] = 'montant du retrait',

	-- Billing Menu
	['billing'] = 'Facture',
	['no_players_nearby'] = 'Aucun joueur à proximité',
	['billing_amount'] = 'Montant de la facture',
	['amount_invalid'] = 'Montant invalide',


	['mechanic'] = 'mecano',
	['drive_to_indicated'] = '~y~Conduisez~s~ jusqu\'à l\'endroit indiqué',
	['mission_canceled'] = 'Mission ~r~annulée~s~',
	['vehicle_list'] = 'sortir Véhicule',
	['work_wear'] = 'tenue de travail',
	['civ_wear'] = 'Tenue civile',
	['deposit_stock'] = 'Déposer Stock',
	['withdraw_stock'] = 'Prendre Stock',
	['boss_actions'] = 'action Patron',
	['service_vehicle'] = 'Véhicule de service',
	['flat_bed'] = 'plateau',
	['tow_truck'] = 'dépaneuse',
	['service_full'] = 'service complet : ',
	['open_actions'] = 'Appuyez sur ~INPUT_CONTEXT~ pour accéder au menu.',
	['harvest'] = 'récolte',
	['harvest_menu'] = 'Appuyez sur ~INPUT_CONTEXT~ pour accéder au menu de récolte.',
	['not_experienced_enough'] = 'Vous n\'êtes ~r~pas assez expérimenté~s~ pour effectuer cette action.',
	['gas_can'] = 'Bouteille de gaz',
	['repair_tools'] = 'Outils réparation',
	['body_work_tools'] = 'Outils Carosserie',
	['blowtorch'] = 'chalumeaux',
	['repair_kit'] = 'kit Réparation',
	['body_kit'] = 'kit Carosserie',
	['craft'] = 'etabli',
	['craft_menu'] = 'appuyez sur ~INPUT_CONTEXT~ pour accéder au menu établi.',
	['billing'] = 'facturation',
	['hijack'] = 'crocheter',
	['repair'] = 'réparer',
	['clean'] = 'nettoyer',
	['imp_veh'] = 'fourrière',
	['place_objects'] = 'placer objets',
	['invoice_amount'] = 'montant de la facture',
	['amount_invalid'] = 'montant invalide',
	['no_players_nearby'] = 'aucun joueur à proximité',
	['no_vehicle_nearby'] = 'there is no nearby vehicle',
	['inside_vehicle'] = 'you can\'t do this from inside the vehicle!',
	['vehicle_unlocked'] = 'véhicule ~g~déverouillé',
	['vehicle_repaired'] = 'véhicule ~g~réparé',
	['vehicle_cleaned'] = 'véhicule ~g~néttoyé',
	['vehicle_impounded'] = 'vehicule ~r~mis en fourrière',
	['must_seat_driver'] = 'vous devez être assis du ~r~côté conducteur!',
	['must_near'] = 'vous devez être ~r~près d\'un véhicule~s~ pour le mettre en fourrière',
	['vehicle_success_attached'] = 'vehicule ~b~attaché~s~ avec succès!',
	['please_drop_off'] = 'veuillez déposer le véhicule à la concession',
	['cant_attach_own_tt'] = '~r~Impossible~s~ d\'attacher votre propre dépanneuse',
	['no_veh_att'] = 'il n\'y a ~r~pas de véhicule~s~ à attacher',
	['not_right_veh'] = 'ce n\'est pas le bon véhicule',
	['veh_det_succ'] = 'vehicule ~b~détattaché~s~ avec succès!',
	['imp_flatbed'] = '~r~Impossible! ~s~Vous devez avoir un ~b~Flatbed ~s~pour ça',
	['objects'] = 'objets',
	['roadcone'] = 'plot',
	['toolbox'] = 'boîte à outils',
	['mechanic_stock'] = 'mecano Stock',
	['quantity'] = 'quantité',
	['invalid_quantity'] = 'quantité invalide',
	['inventory'] = 'inventaire',
	['veh_unlocked'] = '~g~Véhicule déverouillé',
	['hijack_failed'] = '~r~Crochetage raté',
	['body_repaired'] = '~g~Carosserie réparée',
	['veh_repaired'] = '~g~Véhicule réparé',
	['veh_stored'] = 'appuyez sur ~INPUT_CONTEXT~ pour ranger le véhicule.',
	['press_remove_obj'] = 'appuyez sur ~INPUT_CONTEXT~ pour enlever l\'object',
	['please_tow'] = 'veuillez ~y~remorquer~s~ le véhicule',
	['wait_five'] = 'Vous devez ~r~attendre~s~ 5 minutes',
	['must_in_flatbed'] = 'Vous devez être en flatbed pour commencer la mission',
	['not_right_place'] = 'Vous devez être au bon endroit pour faire cela',
	['mechanic_customer'] = 'client mecano',
	['you_do_not_room'] = '~r~Vous n\'avez plus de place',
	['recovery_gas_can'] = 'Récupération de ~b~bouteille de gaz~s~...',
	['recovery_repair_tools'] = 'Récupération d\'~b~Outils réparation~s~...',
	['recovery_body_tools'] = 'Récupération d\'~b~Outils carosserie~s~...',
	['not_enough_gas_can'] = 'Vous n\'avez ~r~pas assez~s~ de bouteille de gaz',
	['assembling_blowtorch'] = 'Assemblage de ~b~Chalumeaux~s~...',
	['not_enough_repair_tools'] = 'Vous n\'avez ~r~pas assez~s~ d\'outils réparation',
	['assembling_repair_kit'] = 'Assemblage de ~b~Kit réparation~s~...',
	['not_enough_body_tools'] = 'Vous n\'avez ~r~pas assez~s~ d\'outils carosserie',
	['assembling_body_kit'] = 'Assemblage de ~b~Kit carosserie~s~...',
	['your_comp_earned'] = 'Votre société a ~g~gagné~s~ ~g~$',
	['you_used_blowtorch'] = 'Vous avez utilisé un ~b~Chalumeau',
	['you_used_repair_kit'] = 'Vous avez utilisé un ~b~Kit de réparation',
	['you_used_body_kit'] = 'Vous avez utilisé un ~b~Kit de carosserie',
	['have_withdrawn'] = 'vous avez pris ~y~x%s~s~ ~b~%s~s~',
	['have_deposited'] = 'vous avez déposé ~y~x%s~s~ ~b~%s~s~',
	['player_cannot_hold'] = 'you do ~r~not~s~ have enough ~y~free space~s~ in your inventory !',


	['gilet_wear1'] = 'Enlever votre gilet orange',
	['cloakroom'] = 'vestiaire',
	['citizen_wear'] = 'Prendre sa fin de service',
	['police_wear'] = 'Prendre son service',
	['gilet_wear'] = 'gilet orange',
	['bullet_wear'] = 'gilet pare-balles',
	['no_outfit'] = 'il n\'y a pas d\'uniforme à votre taille...',
	['open_cloackroom'] = 'appuyez sur ~INPUT_CONTEXT~ pour vous changer',
	-- Armory
	['remove_object'] = 'prendre un Objet',
	['deposit_object'] = 'deposer un objet',
	['get_weapon'] = 'prendre une Arme',
	['put_weapon'] = 'deposer une Arme',
	['buy_weapons'] = 'acheter des Armes',
	['armory'] = 'armurerie',
	['open_armory'] = 'appuyez sur ~INPUT_CONTEXT~ pour ouvrir le coffre de l\'armurerie',
	['armory_owned'] = 'possédé',
	['armory_free'] = 'gratuit',
	['armory_item'] = '$%s',
	['armory_weapontitle'] = 'armurerie - Acheter une arme',
	['armory_componenttitle'] = 'armurerie - Accessoires d\'armes',
	['armory_bought'] = 'vous achetez un ~y~%s~s~ pour ~r~$%s~s~',
	['armory_money'] = 'vous ne pouvez pas acheter cette arme',
	['armory_hascomponent'] = 'vous avez cet accessoire équipé!',
	['get_weapon_menu'] = 'armurerie - Prendre Arme',
	['put_weapon_menu'] = 'armurerie - Déposer Arme',
	-- Vehicles
	['vehicle_menu'] = 'VOS VEHICULES DE SERVICE',
	['vehicle_out'] = 'il y a déja un véhicule de sorti',
	['vehicle_spawner'] = 'appuyez sur ~INPUT_CONTEXT~ pour sortir un véhicule de service',
	['store_vehicle'] = 'appuyez sur ~INPUT_CONTEXT~ pour ranger votre véhicule de service',
	-- Service
	['service_max'] = 'you cannot enter service, max officers in service: %s/%s',
	['service_not'] = '~r~Tu n\'es pas en service',
	['service_anonunce'] = 'service information',
	['service_in'] = '~y~Prise de Service~s~',
	['service_in_announce'] = 'L\'officier ~y~%s~s~ est entrer service!',
	['service_out'] = '~y~Fin de Service~s~',
	['service_out_announce'] = 'L\'officier ~y~%s~s~ a pris sa fin de service.',
	-- Action Menu
	['citizen_interaction'] = 'interaction avec le citoyen',
	['vehicle_interaction'] = 'interaction avec le vehicule',
	['object_spawner'] = 'sortir du materiel',

	['id_card'] = 'Regarder la carte d\'identite',
	['search'] = 'fouiller l\'individu',
	['handcuff'] = 'menotter ou Demenotter',
	['drag'] = 'escorter l\'individu',
	['put_in_vehicle'] = 'mettre l\'individu dans le vehicule',
	['out_the_vehicle'] = 'sortir l\'individu du vehicule',
	['fine'] = 'Amende',
	['unpaid_bills'] = 'gerer les amendes impayes',
	['license_check'] = 'gerer les licences',
	['license_revoke'] = 'revoquer la licence',
	['license_revoked'] = 'votre ~b~%s~s~ a été ~y~révoqué~s~!',
	['licence_you_revoked'] = 'vous avez révoqué un ~b~%s~s~ qui appartenait à ~y~%s~s~',
	['no_players_nearby'] = 'aucun joueur à proximité',
	['being_searched'] = 'vous vous faites ~y~fouillé~s~ par la ~b~Police~s~',
	-- Vehicle interaction
	['vehicle_info'] = 'infos du véhicule',
	['pick_lock'] = 'crocheter le véhicule',
	['vehicle_unlocked'] = 'véhicule ~g~déverouillé~s~',
	['no_vehicles_nearby'] = 'aucun véhicule à proximité',
	['impound'] = 'véhicule en fourrière',
	['impound_prompt'] = 'appuyez sur ~INPUT_CONTEXT~ pour annuler la ~y~saisie du véhicule~s~',
	['impound_canceled'] = 'vous avez annulé la saisie',
	['impound_canceled_moved'] = 'la saisie a été annulée parce que le véhicule a déménagé',
	['impound_successful'] = 'vous avez ~r~saisi~s~ le véhicule',
	['search_database'] = 'vehicle information',
	['search_database_title'] = 'informations sur le véhicule - recherche avec numéro d\'enregistrement',
	['search_database_error_invalid'] = 'ce n\'est ~r~pas~s~ un ~y~numéro d\'enregistrement valide~s~ !',
	['search_database_error_not_found'] = 'ce ~y~numéro d\'enregistrement~s~ n\'est ~r~pas~s~ enregistré sur un véhicule !',
	['search_database_found'] = 'le véhicule est ~y~enregistré~s~ à ~b~%s~s~',
	-- Traffic interaction
	['traffic_interaction'] = 'Interaction routère',
	['cone'] = 'Plot',
	['barrier'] = 'Barriere',
	['spikestrips'] = 'Herse',
	['box'] = 'caisse',
	['cash'] = 'caisse',
	-- ID Card Menu
	['name'] = 'nom: %s',
	['job'] = 'job: %s',
	['sex'] = 'sexe: %s',
	['dob'] = 'DDN: %s',
	['height'] = 'taille: %s',
	['id'] = 'ID: %s',
	['bac'] = 'alcoolémie: %s',
	['unknown'] = 'inconnu',
	['male'] = 'masculin',
	['female'] = 'féminin',
	-- Body Search Menu
	['guns_label'] = '--- Armes ---',
	['inventory_label'] = '--- Inventaire ---',
	['license_label'] = ' --- Licenses ---',
	['confiscate'] = 'Confisquer %s',
	['confiscate_weapon'] = 'confiscate %s with %s bullets',
	['confiscate_inv'] = 'Confisquer %sx %s',
	['confiscate_dirty'] = 'Confisquer argent sale: <span style="color:red;">€%s</span>',
	['you_confiscated'] = 'you confiscated ~y~%sx~s~ ~b~%s~s~ from ~b~%s~s~',
	['got_confiscated'] = '~y~%sx~s~ ~b~%s~s~ were confiscated by ~y~%s~s~',
	['you_confiscated_account'] = 'you confiscated ~g~€%s~s~ (%s) from ~b~%s~s~',
	['got_confiscated_account'] = '~g~€%s~s~ (%s) was confiscated by ~y~%s~s~',
	['you_confiscated_weapon'] = 'you confiscated ~b~%s~s~ from ~b~%s~s~ with ~o~%s~s~ bullets',
	['got_confiscated_weapon'] = 'your ~b~%s~s~ with ~o~%s~s~ bullets was confiscated by ~y~%s~s~',
	['traffic_offense'] = 'infraction au code de la route',
	['minor_offense'] = 'délit mineur',
	['average_offense'] = 'délit moyen',
	['major_offense'] = 'délit grave',
	['fine_total'] = 'amende: %s',
	-- Vehicle Info Menu
	['plate'] = 'n°: %s',
	['owner_unknown'] = 'propriétaire: Inconnu',
	['owner'] = 'propriétaire: %s',
	-- Boss Menu
	['take_company_money'] = 'retirer argent société',
	['deposit_money'] = 'déposer argent',
	['amount_of_withdrawal'] = 'montant du retrait',
	['invalid_amount'] = 'montant invalide',
	['amount_of_deposit'] = 'montant du dépét',
	['open_bossmenu'] = 'appuyez sur ~INPUT_CONTEXT~ pour ouvrir le menu',
	['quantity_invalid'] = 'quantité invalide',
	['have_withdrawn'] = 'vous avez retiré ~y~%sx~s~ ~b~%s~s~',
	['have_deposited'] = 'vous avez déposé ~y~%sx~s~ ~b~%s~s~',
	['quantity'] = 'quantité',
	['inventory'] = 'inventaire',
	['police_stock'] = 'police Stock',
	-- Misc
	['remove_prop'] = 'appuyez sur ~INPUT_CONTEXT~ pour enlever l\'objet',
	--['map_blip'] = 'Commissariat',
	['unrestrained_timer'] = 'you feel your handcuffs slowly losing grip and fading away.',
	-- Notifications
	['alert_police'] = 'alerte police',
	['phone_police'] = 'police',
	['Brottsregister'] = 'Casier Judiciare',

	['properties'] = 'propriétés',
	['clients'] = 'clients',
	['realtor'] = 'agent Immobilier',
	['amount_withdraw'] = 'montant du retrait',
	['invalid_amount'] = 'montant invalide',
	['press_to_access'] = 'appuyez sur ~INPUT_CONTEXT~ pour accéder au menu',
	['amount'] = 'montant',
	['no_play_near'] = 'aucun joueur à proximité',
	['realtors'] = 'agents Immobilier',
	['boss_action'] = 'action Patron',
	['client_poor'] = 'votre client ne peut pas se le permettre',

	-- Property menu
	['property_name'] = 'propriété',
	['property_actions'] = 'actions',
	['property_actionbuttons'] = '{{Assigner [Vente]|sell}} {{Assigner [Location]|rent}} {{GPS|gps}}',

	-- Customer menu
	['customer_client'] = 'client',
	['customer_property'] = 'propriété',
	['customer_agreement'] = 'accord',
	['customer_actions'] = 'actions',
	['customer_contractbuttons'] = '{{Révoquer contrat|revoke}} {{GPS|gps}}',
	['customer_rent'] = 'location',
	['customer_sell'] = 'vente',

	-- Cloakroom
	['gilet_wear1'] = 'Enlever votre gilet orange',
	['cloakroom'] = 'vestiaire',
	['citizen_wear'] = 'Prendre sa fin de service',
	['police_wear'] = 'Prendre son service',
	['gilet_wear'] = 'gilet orange',
	['bullet_wear'] = 'gilet pare-balles',
	['no_outfit'] = 'il n\'y a pas d\'uniforme à votre taille...',
	['open_cloackroom'] = 'appuyez sur ~INPUT_CONTEXT~ pour vous changer',
	-- Armory
	['remove_object'] = 'prendre un Objet',
	['deposit_object'] = 'deposer un objet',
	['get_weapon'] = 'prendre une Arme',
	['put_weapon'] = 'deposer une Arme',
	['buy_weapons'] = 'acheter des Armes',
	['armory'] = 'armurerie',
	['open_armory'] = 'appuyez sur ~INPUT_CONTEXT~ pour ouvrir le coffre de l\'armurerie',
	['armory_owned'] = 'possédé',
	['armory_free'] = 'gratuit',
	['armory_item'] = '$%s',
	['armory_weapontitle'] = 'armurerie - Acheter une arme',
	['armory_componenttitle'] = 'armurerie - Accessoires d\'armes',
	['armory_bought'] = 'vous achetez un ~y~%s~s~ pour ~r~$%s~s~',
	['armory_money'] = 'vous ne pouvez pas acheter cette arme',
	['armory_hascomponent'] = 'vous avez cet accessoire équipé!',
	['get_weapon_menu'] = 'armurerie - Prendre Arme',
	['put_weapon_menu'] = 'armurerie - Déposer Arme',
	-- Vehicles
	['vehicle_menu'] = 'VOS VEHICULES DE SERVICE',
	['vehicle_out'] = 'il y a déja un véhicule de sorti',
	['vehicle_spawner'] = 'appuyez sur ~INPUT_CONTEXT~ pour sortir un véhicule de service',
	['store_vehicle'] = 'appuyez sur ~INPUT_CONTEXT~ pour ranger votre véhicule de service',
	-- Service
	['service_max'] = 'you cannot enter service, max officers in service: %s/%s',
	['service_not'] = '~r~Tu n\'es pas en service',
	['service_anonunce'] = 'service information',
	['service_in'] = '~y~Prise de Service~s~',
	['service_in_announce'] = 'L\'officier ~y~%s~s~ est entrer service!',
	['service_out'] = '~y~Fin de Service~s~',
	['service_out_announce'] = 'L\'officier ~y~%s~s~ a pris sa fin de service.',
	-- Action Menu
	['citizen_interaction'] = 'interaction avec le citoyen',
	['vehicle_interaction'] = 'interaction avec le vehicule',
	['object_spawner'] = 'sortir du materiel',

	['id_card'] = 'Regarder la carte d\'identite',
	['search'] = 'fouiller l\'individu',
	['handcuff'] = 'menotter ou Demenotter',
	['drag'] = 'escorter l\'individu',
	['put_in_vehicle'] = 'mettre l\'individu dans le vehicule',
	['out_the_vehicle'] = 'sortir l\'individu du vehicule',
	['fine'] = 'Amende',
	['unpaid_bills'] = 'gerer les amendes impayes',
	['license_check'] = 'gerer les licences',
	['license_revoke'] = 'revoquer la licence',
	['license_revoked'] = 'votre ~b~%s~s~ a été ~y~révoqué~s~!',
	['licence_you_revoked'] = 'vous avez révoqué un ~b~%s~s~ qui appartenait à ~y~%s~s~',
	['no_players_nearby'] = 'aucun joueur à proximité',
	['being_searched'] = 'vous vous faites ~y~fouillé~s~ par la ~b~Police~s~',
	-- Vehicle interaction
	['vehicle_info'] = 'infos du véhicule',
	['pick_lock'] = 'crocheter le véhicule',
	['vehicle_unlocked'] = 'véhicule ~g~déverouillé~s~',
	['no_vehicles_nearby'] = 'aucun véhicule à proximité',
	['impound'] = 'véhicule en fourrière',
	['impound_prompt'] = 'appuyez sur ~INPUT_CONTEXT~ pour annuler la ~y~saisie du véhicule~s~',
	['impound_canceled'] = 'vous avez annulé la saisie',
	['impound_canceled_moved'] = 'la saisie a été annulée parce que le véhicule a déménagé',
	['impound_successful'] = 'vous avez ~r~saisi~s~ le véhicule',
	['search_database'] = 'vehicle information',
	['search_database_title'] = 'informations sur le véhicule - recherche avec numéro d\'enregistrement',
	['search_database_error_invalid'] = 'ce n\'est ~r~pas~s~ un ~y~numéro d\'enregistrement valide~s~ !',
	['search_database_error_not_found'] = 'ce ~y~numéro d\'enregistrement~s~ n\'est ~r~pas~s~ enregistré sur un véhicule !',
	['search_database_found'] = 'le véhicule est ~y~enregistré~s~ à ~b~%s~s~',
	-- Traffic interaction
	['traffic_interaction'] = 'Interaction routère',
	['cone'] = 'Plot',
	['barrier'] = 'Barriere',
	['spikestrips'] = 'Herse',
	['box'] = 'caisse',
	['cash'] = 'caisse',
	-- ID Card Menu
	['name'] = 'nom: %s',
	['job'] = 'job: %s',
	['sex'] = 'sexe: %s',
	['dob'] = 'DDN: %s',
	['height'] = 'taille: %s',
	['id'] = 'ID: %s',
	['bac'] = 'alcoolémie: %s',
	['unknown'] = 'inconnu',
	['male'] = 'masculin',
	['female'] = 'féminin',
	-- Body Search Menu
	['guns_label'] = '--- Armes ---',
	['inventory_label'] = '--- Inventaire ---',
	['license_label'] = ' --- Licenses ---',
	['confiscate'] = 'Confisquer %s',
	['confiscate_weapon'] = 'confiscate %s with %s bullets',
	['confiscate_inv'] = 'Confisquer %sx %s',
	['confiscate_dirty'] = 'Confisquer argent sale: <span style="color:red;">€%s</span>',
	['you_confiscated'] = 'you confiscated ~y~%sx~s~ ~b~%s~s~ from ~b~%s~s~',
	['got_confiscated'] = '~y~%sx~s~ ~b~%s~s~ were confiscated by ~y~%s~s~',
	['you_confiscated_account'] = 'you confiscated ~g~€%s~s~ (%s) from ~b~%s~s~',
	['got_confiscated_account'] = '~g~€%s~s~ (%s) was confiscated by ~y~%s~s~',
	['you_confiscated_weapon'] = 'you confiscated ~b~%s~s~ from ~b~%s~s~ with ~o~%s~s~ bullets',
	['got_confiscated_weapon'] = 'your ~b~%s~s~ with ~o~%s~s~ bullets was confiscated by ~y~%s~s~',
	['traffic_offense'] = 'infraction au code de la route',
	['minor_offense'] = 'délit mineur',
	['average_offense'] = 'délit moyen',
	['major_offense'] = 'délit grave',
	['fine_total'] = 'amende: %s',
	-- Vehicle Info Menu
	['plate'] = 'n°: %s',
	['owner_unknown'] = 'propriétaire: Inconnu',
	['owner'] = 'propriétaire: %s',
	-- Boss Menu
	['take_company_money'] = 'retirer argent société',
	['deposit_money'] = 'déposer argent',
	['amount_of_withdrawal'] = 'montant du retrait',
	['invalid_amount'] = 'montant invalide',
	['amount_of_deposit'] = 'montant du dépét',
	['open_bossmenu'] = 'appuyez sur ~INPUT_CONTEXT~ pour ouvrir le menu',
	['quantity_invalid'] = 'quantité invalide',
	['have_withdrawn'] = 'vous avez retiré ~y~%sx~s~ ~b~%s~s~',
	['have_deposited'] = 'vous avez déposé ~y~%sx~s~ ~b~%s~s~',
	['quantity'] = 'quantité',
	['inventory'] = 'inventaire',
	['police_stock'] = 'police Stock',
	-- Misc
	['remove_prop'] = 'appuyez sur ~INPUT_CONTEXT~ pour enlever l\'objet',
	--['map_blip'] = 'Commissariat',
	['unrestrained_timer'] = 'you feel your handcuffs slowly losing grip and fading away.',
	-- Notifications
	['alert_police'] = 'alerte police',
	['phone_police'] = 'police',
	['Brottsregister'] = 'Casier Judiciare',

	['taking_service'] = 'prise de service : ',
	['spawn_veh'] = 'sortir véhicule',
	['remove_comp_money'] = 'retirer argent société',
	['deposit_money'] = 'déposer argent',
	['launder_money'] = 'blanchir argent',
	['full_service'] = 'service complet : ',
	['withdraw_amount'] = 'montant du retrait',
	['amount_invalid'] = 'montant invalide',
	['deposit_amount'] = 'montant du dépôt',
	['launder_amount'] = 'montant à blanchir',
	['press_to_open'] = 'appuyez sur ~INPUT_CONTEXT~ pour ~g~accéder~s~ au menu',
	['billing'] = 'facturation',
	['invoice_amount'] = 'montant de la facture',
	['no_players_near'] = 'aucun joueur à proximité',
	['store_veh'] = 'appuyez sur ~INPUT_CONTEXT~ pour ~r~ranger~s~ le véhicule',
	['drive_search_pass'] = 'conduisez à la recherche de ~y~passagers',
	['customer_found'] = 'vous avez ~g~trouvé~s~ un client, conduisez jusqu\'à ce dernier',
	['client_unconcious'] = 'votre client est ~r~inconscient~s~. Cherchez-en un autre.',
	['arrive_dest'] = 'vous êtes ~g~arrivé~s~ à destination',
	['take_me_to_near'] = '~s~Emmenez-moi à~y~ %s~s~, près de~y~ %s',
	['take_me_to'] = '~s~Emmenez-moi à~y~ %s',
	['close_to_client'] = 'vous êtes à proximité du client, approchez-vous de lui',
	['return_to_veh'] = 'veuillez remonter dans votre véhicule pour continuer la mission',
	['only_taxi'] = 'vous ne pouvez ranger que les taxi',
	['must_in_taxi'] = 'vous devez être dans un taxi pour commencer la mission',
	['must_in_vehicle'] = 'vous devez être dans un véhicule pour commencer la mission',
	['have_earned'] = 'vous avez gagné ~g~$',
	['comp_earned'] = 'votre société a gagné ~g~$',
	['deposit_stock'] = 'Déposer Stock',
	['take_stock'] = 'Prendre Stock',
	['boss_actions'] = 'action Patron',
	['mission_complete'] = 'Mission terminée',
	['quantity'] = 'Quantité',
	['quantity_invalid'] = 'Quantité invalide',
	['inventory'] = 'Inventaire',
	['taxi_client'] = 'client Taxi',
	['have_withdrawn'] = 'Vous avez retiré x',
	['added'] = 'Vous avez ajouté x',
	['player_cannot_hold'] = 'vous n\'avez ~r~pas assez~s~ d\' ~y~espace~s~ dans votre inventaire!',


	-- Cloakroom
	['cloakroom']                = 'Vestiaire',
	['citizen_wear']             = 'Tenue civile',
	['barman_outfit']            = 'Tenue de barman',
	['dancer_outfit_1']          = 'Tenue de danse 1',
	['dancer_outfit_2']          = 'Tenue de danse 2',
	['dancer_outfit_3']          = 'Tenue de danse 3',
	['dancer_outfit_4']          = 'Tenue de danse 4',
	['dancer_outfit_5']          = 'Tenue de danse 5',
	['dancer_outfit_6']          = 'Tenue de danse 6',
	['dancer_outfit_7']          = 'Tenue de danse 7',
	['no_outfit']                = 'Il n\'y a pas d\'uniforme à votre taille...',
	['open_cloackroom']          = 'Appuyez sur ~INPUT_CONTEXT~ pour vous changer',

	-- Vault
	['get_weapon']               = 'Prendre une Arme',
	['put_weapon']               = 'Déposer une Arme',
	['get_weapon_menu']          = 'Coffre - Prendre une Arme',
	['put_weapon_menu']          = 'Coffre - Déposer une Arme',
	['get_object']               = 'Prendre un Objet',
	['put_object']               = 'Déposer un Objet',
	['vault']                    = 'Coffre',
	['open_vault']               = 'Appuyez sur ~INPUT_CONTEXT~ pour accéder au coffre',

	-- Fridge
	['get_object']               = 'Prendre un Objet',
	['put_object']               = 'Déposer un Objet',
	['fridge']                   = 'Frigo',
	['open_fridge']              = 'Appuyez sur ~INPUT_CONTEXT~ pour accéder au frigo',
	['unicorn_fridge_stock']     = 'Frigo du Vanilla Unicorn',
	['fridge_inventory']         = 'Contenu du frigo',

	-- Shops
	['shop']                     = 'Boutique du Vanilla Unicorn',
	['shop_menu']                = 'Appuyez sur ~INPUT_CONTEXT~ pour accéder à la boutique.',
	['bought']                   = 'Vous avez acheté ~b~1x ',
	['not_enough_money']         = 'Vous n\'avez ~r~pas assez~s~ d\'argent sur vous.',
	['max_item']                 = 'Vous en portez déjà assez sur vous.',

	-- Vehicles
	['vehicle_menu']             = 'Véhicule',
	['vehicle_out']              = 'Il y a déja un véhicule dehors',
	['vehicle_spawner']          = 'Appuyez sur ~INPUT_CONTEXT~ pour sortir un véhicule',
	['store_vehicle']            = 'Appuyez sur ~INPUT_CONTEXT~ pour ranger le véhicule',
	['service_max']              = 'Service complet : ',
	['spawn_point_busy']         = 'Un véhicule occupe le point de sortie',

	-- Boss Menu
	['take_company_money']       = 'Retirer argent société',
	['deposit_money']            = 'Déposer de l\'argent',
	['amount_of_withdrawal']     = 'Montant du retrait',
	['invalid_amount']           = 'Montant invalide',
	['amount_of_deposit']        = 'Montant du dépôt',
	['open_bossmenu']            = 'Appuyez sur ~INPUT_CONTEXT~ pour ouvrir le menu',
	['invalid_quantity']         = 'Quantité invalide',
	['you_removed']              = 'Vous avez retiré x',
	['you_added']                = 'Vous avez ajouté x',
	['quantity']                 = 'Quantité',
	['inventory']                = 'Inventaire',
	['unicorn_stock']            = 'Stock du Vanilla Unicorn',

	-- Billing Menu
	['billing']                  = 'Facturer l\'individu',
	['no_players_nearby']        = 'Aucun joueur à proximité',
	['billing_amount']           = 'Montant de la facture',
	['amount_invalid']           = 'Montant invalide',

	-- Crafting Menu
	['crafting']                 = 'Mixologie',
	['martini']                  = 'Martini blanc',
	['icetea']                   = 'Ice Tea',
	['drpepper']                 = 'Dr. Pepper',
	['saucisson']                = 'Saucisson',
	['grapperaisin']             = 'Grappe de raisin',
	['energy']                   = 'Energy Drink',
	['jager']                    = 'Jägermeister',
	['limonade']                 = 'Limonade',
	['vodka']                    = 'Vodka',
	['ice']                      = 'Glaçon',
	['soda']                     = 'Soda',
	['whisky']                   = 'Whisky',
	['rhum']                     = 'Rhum',
	['tequila']                  = 'Tequila',
	['menthe']                   = 'Menthe',
	['jusfruit']                 = 'Jus de fruits',
	['jagerbomb']                = 'Jägerbomb',
	['bolcacahuetes']            = 'Cacahuètes',
	['bolnoixcajou']             = 'Noix de cajou',
	['bolpistache']              = 'Pistaches',
	['bolchips']                 = 'Chips',
	['jagerbomb']                = 'Jägerbomb',
	['golem']                    = 'Golem',
	['whiskycoca']               = 'Whisky-coca',
	['vodkaenergy']              = 'Vodka-energy',
	['vodkafruit']               = 'Vodka-jus de fruits',
	['rhumfruit']                = 'Rhum-jus de fruits',
	['teqpaf']                   = 'Teq\'paf',
	['rhumcoca']                 = 'Rhum-coca',
	['mojito']                   = 'Mojito',
	['mixapero']                 = 'Mix Apéro',
	['metreshooter']             = 'Mètre de shooter',
	['jagercerbere']             = 'Jäger Cerbère',
	['assembling_cocktail']      = 'Mélange des différents ingrédients en cours !',
	['craft_miss']               = 'Malheureux échec du mélange...',
	['not_enough']               = 'Pas assez de ~r~ ',
	['craft']                    = 'Mélange terminé de ~g~',

	-- Misc
	--['map_blip']                 = 'Vanilla Unicorn',
	['unicorn']                  = 'Vanilla Unicorn',

	-- Phone
	['unicorn_phone']            = 'Unicorn',
	['unicorn_customer']         = 'Citoyen',

	-- Teleporters
	['e_to_enter_1']             = 'Appuyez sur ~INPUT_PICKUP~ pour passer derrière le bar',
	['e_to_exit_1']              = 'Appuyez sur ~INPUT_PICKUP~ pour passer devant le bar.',
	['e_to_enter_2']             = 'Appuyez sur ~INPUT_PICKUP~ pour monter sur le toit.',
	['e_to_exit_2']              = 'Appuyez sur ~INPUT_PICKUP~ pour descendre dans les bureaux.',

	-- Body Search Menu
	['guns_label'] = '--- Armes ---',
	['inventory_label'] = '--- Inventaire ---',
	['license_label'] = ' --- Licenses ---',
	['confiscate'] = 'Confisquer %s',
	['confiscate_weapon'] = 'confiscate %s with %s bullets',
	['confiscate_inv'] = 'Confisquer %sx %s',
	['confiscate_dirty'] = 'Confisquer argent sale: <span style="color:red;">€%s</span>',
	['you_confiscated'] = 'you confiscated ~y~%sx~s~ ~b~%s~s~ from ~b~%s~s~',
	['got_confiscated'] = '~y~%sx~s~ ~b~%s~s~ were confiscated by ~y~%s~s~',
	['you_confiscated_account'] = 'you confiscated ~g~€%s~s~ (%s) from ~b~%s~s~',
	['got_confiscated_account'] = '~g~€%s~s~ (%s) was confiscated by ~y~%s~s~',
	['you_confiscated_weapon'] = 'you confiscated ~b~%s~s~ from ~b~%s~s~ with ~o~%s~s~ bullets',
	['got_confiscated_weapon'] = 'your ~b~%s~s~ with ~o~%s~s~ bullets was confiscated by ~y~%s~s~',





	-- General
	['cloakroom'] = 'Vestiaire',
	['vine_clothes_civil'] = 'Tenue Civil',
	['vine_clothes_vine'] = 'Tenue de travail',
	['veh_menu'] = 'Garage',
	['spawn_veh'] = 'appuyez sur ~INPUT_CONTEXT~ pour sortir véhicule',
	['amount_invalid'] = 'montant invalide',
	['press_to_open'] = 'appuyez sur ~INPUT_CONTEXT~ pour accéder au menu',
	['billing'] = 'facturation',
	['invoice_amount'] = 'montant de la facture',
	['no_players_near'] = 'aucun joueur à proximité',
	['store_veh'] = 'appuyez sur ~INPUT_CONTEXT~ pour ranger le véhicule',
	['comp_earned'] = 'votre société a gagné ~g~$',
	['deposit_stock'] = 'Déposer Stock',
	['take_stock'] = 'Prendre Stock',
	['boss_actions'] = 'action Patron',
	['quantity'] = 'Quantité',
	['quantity_invalid'] = '~r~Quantité invalide~s~',
	['inventory'] = 'Inventaire',
	['have_withdrawn'] = 'Vous avez retiré x',
	['added'] = 'Vous avez ajouté x',
	['not_enough_place'] = 'Vous n\'avez plus de place',
	['sale_in_prog'] = 'Revente en cours...',
	['van'] = 'Camion de travail',
	['open_menu'] = ' ',

	-- A modifier selon l'entreprise
	['vigneron_client'] = 'client vigne',
	['transforming_in_progress'] = 'Transformation du raisin en cours',
	['raisin_taken'] = 'Vous être en train de ramasser du raisin',
	['press_traitement'] = 'appuyez sur ~INPUT_CONTEXT~ pour transformer votre raisin',
	['press_collect'] = 'appuyez sur ~INPUT_CONTEXT~ pour récolter du raisin',
	['press_sell'] = 'appuyez sur ~INPUT_CONTEXT~ pour vendre vos produits',
	['no_jus_sale'] = 'Vous n\'avez plus ou pas assez de jus de raisin',
	['no_vin_sale'] = 'Vous n\'avez plus ou pas assez de vin',
	['not_enough_raisin'] = 'Vous n\'avez plus de raisin',
	['grand_cru'] = '~g~Génial, un grand cru !~s~',
	['no_product_sale'] = 'Vous n\'avez plus de produits',
	['press_traitement_jus'] = 'appuyez sur ~INPUT_CONTEXT~ pour transformer votre raisin',
	['used_jus'] = 'Vous avez bu du jus de raisin',
	['used_grand_cru'] = 'Vous avez bu une bouteille de grand cru',
	['not_enough_in_society'] = 'il n\'y à plus assez ~r~de cet objet~s~ dans la societé!',
	['player_cannot_hold'] = 'vous n\'avez ~r~pas~s~ assez ~y~d\'espace~s~ dans votre inventaire!',
	['vehicle_belongs'] = 'le véhicule avec la plaque ~y~%s~s~ est désormais à ~b~vous~s~',
	['broke_company'] = 'vous n\avez pas assez d\'argent sur le compte de la societé',
	['license_missing'] = 'you don\'t have a driver\'s license!',
	['purchase_type'] = 'type d\'achat',
	['society_type'] = 'societé',
	['staff_type'] = 'personnel',
	['buy_vehicle_shop'] = 'acheter %s pour $%s?',
	['buy_vehicle'] = 'acheter véhicule',
	['car_dealer'] = 'concessionnaire',
	['shop_awaiting_model'] = 'the vehicle is currently ~g~DOWNLOADING & LOADING~s~ please wait',
	['create_bill'] = 'créer facture',
	['dealer_boss'] = 'concessionnaire - Patron',
	['delivered'] = 'véhicule ~g~rendu~s~ au concessionnaire',
	['depop_vehicle'] = 'rentrer véhicule',
	['return_provider'] = 'rendre le véhicule',
	['get_rented_vehicles'] = 'véhicules en location',
	['invalid_amount'] = 'le montant est invalide',
	['invoice_amount'] = 'montant de la facture',
	['no'] = 'non',
	['yes'] = 'oui',
	['no_players'] = 'aucun joueur à proximité',
	['not_enough_money'] = 'vous n\'avez pas assez d\'argent sur vous',
	['not_rental'] = 'ce n\'est pas un ~r~véhicule de location~s~',
	['not_yours'] = 'ce véhicule ne vous appartient pas',
	['paid_rental'] = 'vous avez ~g~payé~s~ votre location de véhicule: ~g~$%s~s~',
	['pop_vehicle'] = 'sortir véhicule',
	['rent_vehicle'] = 'concessionnaire - Véhicules en location',
	['return_provider_menu'] = 'concessionnaire - Retour de véhicule',
	['rental_amount'] = 'contant de la location',
	['sell_menu'] = 'appuyez sur ~INPUT_CONTEXT~ pour vendre ~y~%s~s~ au prix de ~g~$%s~s~',
	['set_vehicle_owner_rent'] = 'attribuer véhicule [Location]',
	['set_vehicle_owner_sell'] = 'attribuer véhicule [Vente]',
	['set_vehicle_owner_sell_society'] = 'attribuer véhicule [Vente] [Société]',
	['shop_menu'] = 'appuyez sur ~INPUT_CONTEXT~ pour accéder au menu',
	['generic_shopitem'] = '$%s',
	['vehicle_dealer'] = 'concessionnaire - Véhicules',
	['vehicle_menu'] = 'appuyez sur ~INPUT_CONTEXT~ pour rendre votre véhicule',
	['vehicle_purchased'] = 'vous avez acheté un véhicule',
	['vehicle_set_owned'] = 'le véhicule ~y~%s~s~ a été attribué à ~b~%s~s~',
	['vehicle_set_rented'] = 'le véhicule ~y~%s~s~ a été loué à ~b~%s~s~',
	['vehicle_sold_for'] = 'le ~b~%s~s~ a été ~y~vendu~s~ pour ~g~$%s~s~',
	['vehicle_sold_to'] = 'véhicule ~y~%s~s~ vendu à ~b~%s~s~',
	['deposit_stock'] = 'déposer Stock',
	['take_stock'] = 'prendre Stock',
	['dealership_stock'] = 'concession Stock',
	['amount'] = 'quantité',
	['quantity_invalid'] = 'quantité invalide',
	['inventory'] = 'inventaire',
	['dealership'] = 'concession',
	['dealer_customers'] = 'client concession',
	['have_withdrawn'] = 'vous avez retiré ~y~x%s~s~ ~b~%s~s~',
	['have_deposited'] = 'vous avez deposé ~y~x%s~s~ ~b~%s~s~',
	['boss_actions'] = 'actions du chef',

	-- sold vehicles
	['boss_sold'] = 'liste des véhicule vendu',
	['customer_client'] = 'nom du client',
	['customer_model'] = 'modèle de véhicule',
	['customer_plate'] = 'plaque d\'immatriculation',
	['customer_soldby'] = 'votre vehicule a ete vendu par',
	['customer_date'] = 'date',
}